-- AlterTable
ALTER TABLE "Reminder" ADD COLUMN     "body" TEXT NOT NULL DEFAULT 'ERROR_DEFAULT_MISSING_body',
ADD COLUMN     "from" TEXT NOT NULL DEFAULT 'ERROR_DEFAULT_MISSING_from',
ADD COLUMN     "subject" TEXT NOT NULL DEFAULT 'ERROR_DEFAULT_MISSING_subject',
ADD COLUMN     "template" TEXT,
ADD COLUMN     "to" TEXT NOT NULL DEFAULT 'ERROR_DEFAULT_MISSING_to';
